spring:
  datasource:
    url: jdbc:h2:mem:userappdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-userapp

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8081